# ASP.NET Core
# Compile v
pruebe proyectos deASP.NET Core con destino . .NET . Core.
# Agregue pasosque ejecuten pruebas, creen un paquete NuGet, implementen y más:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

desencadenador:

-main

grupo:
.vmImage: ubuntu-latest

variables:
buildConfiguration: 'Release'

pasos :
- script: dotnet build -- configuration $(buildConfiguration)
.displayName: 'dotnet build $(buildConfiguration) '